### ISSUE TITLE
Undefined function money_format()

### ISSUE THREAD

**Issue by livevasiliy** [freshbitsweb/laravel-cart-manager#11]
**Describe the bug**

I'm using your official repository demo project. I'm installing packages, setup .env config & startup local server using Laravel server `php artisan serve`, but I get on root page next error from Laravel.
`Call to undefined function Freshbitsweb\LaravelCartManager\Core\money_format()`

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/15705591/59499433-729c3300-8ea8-11e9-9a3c-bb6f06f364f4.png)

**Additional context**

**Comment by gauravmak** [comment]
We will check

**Comment by gauravmak** [comment]
@livevasiliy `money_format()` is not supported on the Windows platform. I just replaced it with NumberFormatter in the new version. Thanks.
