### ISSUE TITLE
incrementQuantityAt There is no item in the cart at the specified index.

### ISSUE THREAD

**Issue by mirza-alim-m** [freshbitsweb/laravel-cart-manager#14]
protected function existenceCheckFor($cartItemIndex)
    {
        if (! $this->items->has($cartItemIndex)) {
            throw new ItemMissing('There is no item in the cart at the specified index.');
        }
    }

Why do I always get false? Where does has() function come from?
$this->items returns array of object, doesn't it?
And $cartItemIndex is id column of cart_items table, isn't it?

**Comment by mirza-alim-m** [comment]
I'm sorry. I now realize that $cartItemIndex is index of cartItems array.
But why use index of array while we have cart_items.id ? Index may change if people reorder the array.

**Comment by gauravmak** [comment]
Hi @mirza-alim-m 

We initially started with `id` of the cart items but there are a few situations where it becomes hard.

For example, if user tries to add an item that already exists, we increase the quantity of that item. And in that case, the front end needs to be notified about the same. It gets complex.

So, we are always returning full cart after each add/update and the front end can re-render the whole cart.

I hope that was helpful, thanks.
