### ISSUE TITLE
 Trying to access array offset on value of type null

### ISSUE THREAD

**Issue by FIRDOUS-BHAT** [freshbitsweb/laravel-cart-manager#21]
In CartManagerServiceProvider.php line 49:
                                                       
  Trying to access array offset on value of type null  

Got this error just after,

`composer require freshbitsweb/laravel-cart-manager
`

**Comment by gauravmak** [comment]
I just tried it and it worked well as expected.

Please make sure that all [the requirements](https://github.com/freshbitsweb/laravel-cart-manager#requirements) are met. Thanks -
