### ISSUE TITLE
cart()->toArray() items is an empty array

### ISSUE THREAD

**Issue by Majdiden** [freshbitsweb/laravel-cart-manager#23]
cart is not showing items although the items exist in the cart_items table, it's returning an empty array
i couldn't figure it out

**Comment by gauravmak** [comment]
Is the feature to add a new item to the cart working?

**Comment by Majdiden** [comment]
yes, it returns all the item's data but the cart() returns an empty one

**Comment by gauravmak** [comment]
We will not be able to help without more details. The quickest way to solve this: Can you please add to the failing test?
