### ISSUE TITLE
instalation on laravel 6 for api (guard name = api)

### ISSUE THREAD

**Issue by k2gsalem** [freshbitsweb/laravel-cart-manager#24]
not installing this error is showing on composer require freshbitsweb/laravel-cart-manager.

error
------
In CartManagerServiceProvider.php line 49:
                                          
Trying to access array offset on value of type null ,

Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1

Installation failed, reverting ./composer.json to its original content.

**Comment by gauravmak** [comment]
Seems like it can't find the configuration.

Can you try in a fresh project and see if it happens?

**Comment by k2gsalem** [comment]
installing after config:clear  now working ....
