### ISSUE TITLE
is possible (shipping charge & tax & custom field ) each item dynamically getting from database?

### ISSUE THREAD

**Issue by k2gsalem** [freshbitsweb/laravel-cart-manager#26]
is possible (shipping charge & tax & custom field ) each item dynamically getting from the database?
cart_manager.php to database

**Comment by gauravmak** [comment]
You can call getter methods for [cart attributes](https://github.com/freshbitsweb/laravel-cart-manager/blob/master/README.md#get-cart-individual-attributes).

Example - `$subtotal = cart()->getSubtotal();`
