### ISSUE TITLE
Laravel 8 Support

### ISSUE THREAD

**Issue by TrunkNetworks** [freshbitsweb/laravel-cart-manager#27]
**Is your feature request related to a problem? Please describe.**
I cannot upgrade my app to Laravel 8, please update your composer.json dependency file

**Describe the solution you'd like**
Add Laravel 8, to your composer.json dependency file

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by gauravmak** [comment]
Released, thanks.

**Comment by TrunkNetworks** [comment]
Thank you
