### ISSUE TITLE
extended your package for api please check if you thinks its helpful for others.

### ISSUE THREAD

**Issue by yaseenranta** [freshbitsweb/laravel-cart-manager#28]
https://github.com/yaseenranta/ranta-cartapi

**Comment by gauravmak** [comment]
Hi,

What is the goal of the package? What does API support mean here?
Sorry if I missed anything.

**Comment by yaseenranta** [comment]
Thanks for reply.

Its return cart id which helpful for api
add,update,delete item from specific cart using cart id.

**Comment by gauravmak** [comment]
okay, thanks for sharing. I suggest you work on the documentation more :)
