### ISSUE TITLE
User input to update cart quantity

### ISSUE THREAD

**Issue by cxcheng93** [freshbitsweb/laravel-cart-manager#29]
**Is your feature request related to a problem? Please describe.**
If the user want to update the cartItems quantity at big number, it's good to have a method to update the quantity with input instead of one by one. 

**Describe the solution you'd like**
```
/**
     * Set the quantity of a cart item.
     *
     * @param int Index of the cart item
     * @param int quantity to be increased
     * @return array
     */
    public function setQuantityAt($cartItemIndex, $quantity = 1)
    {
        $this->existenceCheckFor($cartItemIndex);

        $this->items[$cartItemIndex]->quantity = $quantity;

        $this->cartDriver->setCartItemQuantity(
            $this->items[$cartItemIndex]->id,
            $this->items[$cartItemIndex]->quantity
        );

        return $this->cartUpdates();
    }

```
**Describe alternatives you've considered**
Add a new method in CartItemsManager to let user update the quantity

**Comment by gauravmak** [comment]
It's a good feature request. I am open to a PR for the same.

**Comment by gauravmak** [comment]
Done with #30
