### ISSUE TITLE
Why package not support float numbers?

### ISSUE THREAD

**Issue by maiskiykot** [freshbitsweb/laravel-cart-manager#38]
I tried your demo package. It's not support float numbers. Why? How I can use for quantity numbers as 0,5, 1,5, etc? Thank you!

**Comment by hirenkeraliya** [comment]
It's a nice idea. You can also make a contribution to this package by giving us a PR for this.

@maiskiykot  Are you able to give the PR?

**Comment by maiskiykot** [comment]
Sorry, but I simply give other package with support of float numbers.

**Comment by gauravmak** [comment]
No problem. Please do share the link to the package so that others with similar requirements can also take the benefit.
