### ISSUE TITLE
configuration options

### ISSUE THREAD

**Issue by tariqtraders** [freshbitsweb/laravel-cart-manager#9]
Change in configuration options 

I want to apply 0% tax. I have updated in cart_manager.php at following lines

`'tax_percentage' => 0,`

but still it gives 6% tax 

can you please tell how i can make tax 0% and shipping 0% and other configurations 0% 

thanks

**Comment by gauravmak** [comment]
@tariqtraders Thank for pointing this out. We will check that.

**Comment by gauravmak** [comment]
@tariqtraders I tried and it works as expected. Please share the demo if possible. Thanks.
